name: "Aviator Test Uploader"
description: "Uploads JunitXML files to Aviator for processing."
branding:
  color: yellow
  icon: activity
inputs:
  assets:
    description: "File path of assets to upload"
    required: true
  aviator_api_token:
    description: "The Aviator API token specific to your account."
    required: true
  assets_required:
    description: "Whether assets should be required. If true, the action will fail if no test files are found."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Checkout upload action directory
      uses: actions/checkout@v3
      with:
        repository: aviator-co/upload-action
        path: upload-action
    - name: Upload to Aviator
      env:
        ASSETS: ${{ inputs.assets }}
        AVIATOR_API_TOKEN: ${{ inputs.aviator_api_token }}
        ASSETS_REQUIRED: ${{ inputs.assets_required }}
      run: bash ${GITHUB_WORKSPACE}/upload-action/upload.sh
      shell: bash
